const shops = [
  {
    shopId: "S001",
    ownerId: "O001",
    shopName: "Woodcraftify",
    shopDescription: "Crafting Excellence, Preserving Traditions, Shaping the Future",
    shopLogo: "../assets/images/woodcrafts_logo.jpg",
    location: "Baguio City, Philippines",
    contactNumber: "+63 912 345 6789",
    email: "contact@woodcrafts.ph",
    dateCreated: "2024-06-15",
    products: ["P001", "P003"]
  }
]

const categories = [
  {
    categoryId: "C001",
    categoryName: "Tables",
    categoryDescription: "A variety of tables ranging from dining to coffee tables, crafted from Cordilleran wood with traditional designs."
  },
  {
    categoryId: "C002",
    categoryName: "Chairs",
    categoryDescription: "Handcrafted wooden chairs, benches, and rocking chairs, offering comfort and style with a touch of tradition."
  },
  {
    categoryId: "C003",
    categoryName: "Cabinets",
    categoryDescription: "Spacious wooden cabinets and wardrobes, perfect for storage, with intricate Cordilleran carvings."
  },
  {
    categoryId: "C004",
    categoryName: "Shelves",
    categoryDescription: "Multi-layered wooden shelves for storage and display, blending functionality with traditional craftsmanship."
  },
  {
    categoryId: "C005",
    categoryName: "Beds",
    categoryDescription: "Traditional wooden bed frames with beautiful Cordilleran carvings, providing both comfort and style."
  },
  {
    categoryId: "C006",
    categoryName: "Sculptures",
    categoryDescription: "Intricately carved wooden sculptures inspired by Cordilleran culture, symbolizing strength and tradition."
  },
  {
    categoryId: "C007",
    categoryName: "Wall Art",
    categoryDescription: "Beautifully carved wooden wall art and traditional wall hangings that add a cultural touch to any space."
  },
  {
    categoryId: "C008",
    categoryName: "Lamps",
    categoryDescription: "Eco-friendly bamboo and wooden lamps that bring warmth and natural beauty to any room."
  },
  {
    categoryId: "C009",
    categoryName: "Containers",
    categoryDescription: "Handwoven baskets and wooden boxes, perfect for storage or decoration, made from natural materials."
  },
  {
    categoryId: "C010",
    categoryName: "Home Décor",
    categoryDescription: "A variety of wooden home décor items, including candle holders, bowls, and room dividers, crafted with traditional designs."
  }
];


const featuredProducts = ["P003", "P017", "P019"];

const products = [
  {
    productId: "P001",
    shopId: "S001",
    productName: "Cordilleran Wooden Dining Table",
    productDescription: "A handcrafted wooden dining table made from sustainable Cordilleran wood, featuring traditional carvings.",
    productImage: "dining_table.jpg",
    price: 15000,
    availableQuantity: 5,
    dateAdded: "2024-08-10",
    category: "Tables",
    tags: ["Dining", "Traditional", "Wooden"],
    dimensions: { length: 200, width: 100, height: 75 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P002",
    shopId: "S002",
    productName: "Bontoc Wooden Bench",
    productDescription: "A sturdy and elegantly designed bench inspired by Bontoc craftsmanship.",
    productImage: "bontoc_bench.jpg",
    price: 8000,
    availableQuantity: 10,
    dateAdded: "2024-08-12",
    category: "Chairs",
    tags: ["Bench", "Traditional", "Handcrafted"],
    dimensions: { length: 150, width: 50, height: 45 },
    materials: ["Bamboo", "Cordilleran Wood"],
  },
  {
    productId: "P003",
    shopId: "S003",
    productName: "Ifugao Wooden Sculpture",
    productDescription: "An intricately carved Ifugao wooden sculpture symbolizing strength and resilience.",
    productImage: "ifugao_sculpture.jpg",
    price: 5000,
    availableQuantity: 20,
    dateAdded: "2024-08-15",
    category: "Sculptures",
    tags: ["Sculpture", "Art", "Cultural"],
    dimensions: { length: 30, width: 20, height: 40 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P004",
    shopId: "S001",
    productName: "Cordilleran Coffee Table",
    productDescription: "A low wooden coffee table with a natural finish, perfect for cozy spaces.",
    productImage: "coffee_table.jpg",
    price: 7000,
    availableQuantity: 7,
    dateAdded: "2024-08-10",
    category: "Tables",
    tags: ["Coffee Table", "Natural", "Rustic"],
    dimensions: { length: 120, width: 60, height: 45 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P005",
    shopId: "S004",
    productName: "Sagada Wooden Shelf",
    productDescription: "A multi-layered wooden shelf that blends functionality with Sagada's artistic touch.",
    productImage: "sagada_shelf.jpg",
    price: 12000,
    availableQuantity: 8,
    dateAdded: "2024-08-18",
    category: "Shelves",
    tags: ["Shelf", "Storage", "Handmade"],
    dimensions: { length: 100, width: 40, height: 180 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P006",
    shopId: "S002",
    productName: "Kalinga Wooden Chair",
    productDescription: "A traditional Kalinga chair with intricate woodwork and a comfortable design.",
    productImage: "kalinga_chair.jpg",
    price: 6000,
    availableQuantity: 12,
    dateAdded: "2024-08-14",
    category: "Chairs",
    tags: ["Chair", "Traditional", "Comfortable"],
    dimensions: { length: 70, width: 70, height: 90 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P007",
    shopId: "S003",
    productName: "Mountain Province Wooden Cabinet",
    productDescription: "A solid wood cabinet with ample storage, showcasing the craftsmanship of Mountain Province.",
    productImage: "cabinet.jpg",
    price: 25000,
    availableQuantity: 3,
    dateAdded: "2024-08-19",
    category: "Cabinets",
    tags: ["Cabinet", "Storage", "Durable"],
    dimensions: { length: 120, width: 60, height: 200 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P008",
    shopId: "S005",
    productName: "Cordilleran Wooden Wall Art",
    productDescription: "A beautifully carved wall art piece depicting traditional Cordilleran patterns.",
    productImage: "wall_art.jpg",
    price: 4500,
    availableQuantity: 15,
    dateAdded: "2024-08-16",
    category: "Wall Art",
    tags: ["Wall Art", "Decor", "Cultural"],
    dimensions: { length: 100, width: 2, height: 50 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P009",
    shopId: "S004",
    productName: "Baguio Wooden Rocking Chair",
    productDescription: "A classic rocking chair made from durable wood, offering comfort and style.",
    productImage: "rocking_chair.jpg",
    price: 9000,
    availableQuantity: 6,
    dateAdded: "2024-08-17",
    category: "Chairs",
    tags: ["Rocking Chair", "Comfort", "Classic"],
    dimensions: { length: 110, width: 60, height: 100 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P010",
    shopId: "S005",
    productName: "Cordilleran Bamboo Lamp",
    productDescription: "An eco-friendly bamboo lamp that adds warmth and a natural touch to any space.",
    productImage: "bamboo_lamp.jpg",
    price: 3000,
    availableQuantity: 10,
    dateAdded: "2024-08-20",
    category: "Lamps",
    tags: ["Lamp", "Eco-Friendly", "Handmade"],
    dimensions: { length: 20, width: 20, height: 60 },
    materials: ["Bamboo", "Cordilleran Wood"],
  },
  {
    productId: "P011",
    shopId: "S002",
    productName: "Traditional Wooden Bed",
    productDescription: "A traditional wooden bed frame with beautiful Cordilleran carvings, perfect for any bedroom.",
    productImage: "wooden_bed.jpg",
    price: 18000,
    availableQuantity: 5,
    dateAdded: "2024-08-22",
    category: "Beds",
    tags: ["Bed", "Traditional", "Comfort"],
    dimensions: { length: 200, width: 160, height: 50 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P012",
    shopId: "S003",
    productName: "Handwoven Basket",
    productDescription: "A beautifully handwoven basket made from natural materials, perfect for storage or decoration.",
    productImage: "basket.jpg",
    price: 2500,
    availableQuantity: 20,
    dateAdded: "2024-08-24",
    category: "Containers",
    tags: ["Basket", "Handwoven", "Eco-Friendly"],
    dimensions: { length: 50, width: 50, height: 30 },
    materials: ["Bamboo", "Abaca"],
  },
  {
    productId: "P013",
    shopId: "S004",
    productName: "Wooden Jewelry Box",
    productDescription: "A small wooden jewelry box with intricate carvings, perfect for storing your precious items.",
    productImage: "jewelry_box.jpg",
    price: 3500,
    availableQuantity: 15,
    dateAdded: "2024-08-23",
    category: "Containers",
    tags: ["Jewelry Box", "Wooden", "Handcrafted"],
    dimensions: { length: 20, width: 15, height: 10 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P014",
    shopId: "S005",
    productName: "Cordilleran Wooden Bedside Table",
    productDescription: "A handcrafted wooden bedside table with a minimalist design and natural wood finish.",
    productImage: "bedside_table.jpg",
    price: 6000,
    availableQuantity: 8,
    dateAdded: "2024-08-25",
    category: "Tables",
    tags: ["Bedside Table", "Minimalist", "Wooden"],
    dimensions: { length: 50, width: 40, height: 60 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P015",
    shopId: "S001",
    productName: "Bamboo Candle Holder",
    productDescription: "A bamboo candle holder that adds a touch of nature to any room, perfect for creating a cozy ambiance.",
    productImage: "candle_holder.jpg",
    price: 1200,
    availableQuantity: 25,
    dateAdded: "2024-08-26",
    category: "Home Décor",
    tags: ["Candle Holder", "Bamboo", "Eco-Friendly"],
    dimensions: { length: 15, width: 15, height: 20 },
    materials: ["Bamboo"],
  },
  {
    productId: "P016",
    shopId: "S002",
    productName: "Cordilleran Wooden Wardrobe",
    productDescription: "A spacious wooden wardrobe with traditional Cordilleran carvings, providing both style and functionality.",
    productImage: "wardrobe.jpg",
    price: 28000,
    availableQuantity: 4,
    dateAdded: "2024-08-27",
    category: "Cabinets",
    tags: ["Wardrobe", "Traditional", "Storage"],
    dimensions: { length: 180, width: 60, height: 220 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P017",
    shopId: "S003",
    productName: "Ifugao Carved Wooden Bowl",
    productDescription: "A beautifully carved wooden bowl inspired by Ifugao culture, perfect for serving or decoration.",
    productImage: "carved_bowl.jpg",
    price: 3000,
    availableQuantity: 18,
    dateAdded: "2024-08-28",
    category: "Home Décor",
    tags: ["Bowl", "Carved", "Traditional"],
    dimensions: { length: 30, width: 30, height: 15 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P018",
    shopId: "S004",
    productName: "Wooden Room Divider",
    productDescription: "A foldable wooden room divider with intricate carvings, offering both privacy and style.",
    productImage: "room_divider.jpg",
    price: 10000,
    availableQuantity: 6,
    dateAdded: "2024-08-29",
    category: "Home Décor",
    tags: ["Room Divider", "Carved", "Functional"],
    dimensions: { length: 150, width: 2, height: 180 },
    materials: ["Cordilleran Wood"],
  },
  {
    productId: "P019",
    shopId: "S005",
    productName: "Cordilleran Wall Hanging",
    productDescription: "A traditional wall hanging made from natural fibers and wooden elements, perfect for adding a cultural touch to your home.",
    productImage: "wall_hanging.jpg",
    price: 3500,
    availableQuantity: 12,
    dateAdded: "2024-08-30",
    category: "Wall Art",
    tags: ["Wall Hanging", "Cultural", "Handcrafted"],
    dimensions: { length: 80, width: 2, height: 120 },
    materials: ["Cordilleran Wood", "Natural Fibers"],
  }
 ]